import org.gradle.kotlin.dsl.project

/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version("0.7.0")
}

rootProject.name = "gifting"

include(":common:iam-enterprise-directory-client")
